CREATE MULTISET TABLE DEV_RBI_EDS.RBI_SRC_SYSCODE_SF
 , NO FALLBACK 
 , NO BEFORE JOURNAL
 , NO AFTER JOURNAL
 , CHECKSUM = DEFAULT
 , DEFAULT MERGEBLOCKRATIO (
 syscode_key SMALLINT NOT NULL,
syscode_id CHAR (18) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL ,
own_id CHAR (18) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL ,
own_key INTEGER NOT NULL, --user
src_del_flg BYTEINT  NOT NULL ,
syscode VARCHAR (10) CHARACTER SET LATIN NOT CASESPECIFIC ,

cstm_desc VARCHAR (255) CHARACTER SET LATIN NOT CASESPECIFIC ,
cstm_isactv_flg BYTEINT  NOT NULL ,
cstm_mkt SMALLINT  ,
cstm_zn SMALLINT  ,
cstm_typ VARCHAR (255) CHARACTER SET LATIN NOT CASESPECIFIC ,
cstm_eclipse_syst VARCHAR (255) CHARACTER SET LATIN NOT CASESPECIFIC ,
cstm_bdgt_dma VARCHAR (255) CHARACTER SET LATIN NOT CASESPECIFIC ,

src_cre_ts TIMESTAMP(0)  NOT NULL ,
--src_cre_by_id CHAR (18) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL ,
--cre_by_key INTEGER NOT NULL,
src_lst_mdfd_ts TIMESTAMP(0)  NOT NULL ,
--src_lst_mdfd_by_id CHAR (18) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL ,
--lst_mdfd_by_key INTEGER NOT NULL,
--syst_modstmp_ts TIMESTAMP(0)  NOT NULL ,
src_lst_vw_ts TIMESTAMP(0)  ,
src_lst_rfnc_ts TIMESTAMP(0)  ,

 eff_start_ts TIMESTAMP(0) NOT NULL ,
 eff_end_ts TIMESTAMP(0) NOT NULL ,
 current_flg CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL DEFAULT 'Y' COMPRESS ('N','Y'),
 cre_ts TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
 updt_ts TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
 etl_prcs_dt DATE FORMAT 'yyyy-mm-dd' NOT NULL,
 src_system_key BYTEINT NOT NULL,
 ld_seq_nbr INTEGER NOT NULL
 ) PRIMARY INDEX upi.rbi_src_syscode_sf ( syscode_key)